name: Evalu8
options:
  bundleIdPrefix: com.nollis
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true

packages: {}

targets:
  Evalu8:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
      - path: Domain
      - path: Data
      - path: Presentation
      - path: Supporting
      - path: Resources
        type: resource
    resources:
      - path: Resources/Assets.xcassets
        type: assetCatalog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nollis.evalu8
        PRODUCT_NAME: Evalu8
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited)"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "We need speech recognition to convert your voice input into text for quick decision creation."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "We need microphone access to record your voice for quick decision creation."
        ENABLE_PREVIEWS: YES
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Evalu8
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
        UIApplicationSupportsIndirectInputEvents: YES
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSSpeechRecognitionUsageDescription: "We need speech recognition to convert your voice input into text for quick decision creation."
        NSMicrophoneUsageDescription: "We need microphone access to record your voice for quick decision creation."
        UIBackgroundModes:
          - remote-notification
    entitlements:
      path: Evalu8.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.nollis.evalu8
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.security.application-groups: []
    dependencies:
      - framework: Speech.framework
        embed: false
      - framework: AVFoundation.framework
        embed: false
      - framework: CoreData.framework
        embed: false
      - framework: CloudKit.framework
        embed: false
    capabilities:
      CloudKit:
        containers:
          - iCloud.com.nollis.evalu8
      background-modes:
        - remote-notification

  Evalu8Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nollis.evalu8Tests
        PRODUCT_NAME: $(TARGET_NAME)
        SWIFT_VERSION: "5.9"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Evalu8.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Evalu8"
    dependencies:
      - target: Evalu8

  Evalu8UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: UITests
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nollis.evalu8UITests
        PRODUCT_NAME: $(TARGET_NAME)
        SWIFT_VERSION: "5.9"
        TEST_TARGET_NAME: Evalu8
    dependencies:
      - target: Evalu8

schemes:
  Evalu8:
    build:
      targets:
        Evalu8: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - Evalu8Tests
        - Evalu8UITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

